### ISSUE TITLE
reading dataset: quote chars 

### ISSUE THREAD

**Issue by mkuhn** [JungeAlexander/cocoscore#15]
In `data_tools.py` / `load_data_frame`, I needed to disable quoting to correctly read my messy MEDLINE data: 

```
    data_df = pd.read_csv(data_frame_path, sep='\t', header=None, index_col=False,
                          names=column_names, quoting=3)
```

`3` corresponds to the constant `QUOTE_NONE` of some pandas module...

**Comment by JungeAlexander** [comment]
Hi @mkuhn, thanks for reporting this! I have not seen this myself but I suspect that the problem is related to either `\t`, `"` or newline characters in the text input. Do you have an example dataset I could play around with to find a way to circumvent these issues in the future? If not, let me know and I'll try to create some toy examples myself.
For my own reference, the QUOTE_NONE constant is documented here in the `csv` module [here](https://docs.python.org/3/library/csv.html#csv.QUOTE_NONE) which is mentioned in `pandas.read_csv`
